[package]
name = "rusty_fractals_common"
version = "0.1.0"
edition = "2021"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
rgb = "0.8"

[badges]
maintenance = { status = "actively-developed" }
