[package]
name = "rusty_fractals_common"
version = "0.1.0"
edition = "2021"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
image = "0.24.5"

[badges]
maintenance = { status = "actively-developed" }
