[package]
name = "fractal_head"
version = "0.1.0"
edition = "2024"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
rusty_fractals_core = { path = "../rusty_fractals_core" }
rusty_fractals_common = { path = "../rusty_fractals_common" }
