[package]
name = "rusty_fractals_core"
version = "0.1.0"
edition = "2021"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
rusty_fractals_common = { path = "../rusty_fractals_common" }
num_cpus = "1.15.0"
colored = "2"
rayon = "1.5"
image = "0.24.5"
rand = "0.8.5"
fltk = "1.3.27"
rgb = "0.8"

[badges]
maintenance = { status = "actively-developed" }
