[package]
name = "rusty_fractals_core"
version = "0.1.0"
edition = "2021"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
rusty_fractals_domain = { path = "../rusty_fractals_domain" }
rusty_fractals_result = { path = "../rusty_fractals_result" }
rusty_fractals_common = { path = "../rusty_fractals_common" }
num_cpus = "1.15.0"
colored = "2"
rayon = "1.5"
image = "0.24.5"

[badges]
maintenance = { status = "actively-developed" }
