[package]
name = "rusty_fractals_core"
version = "0.1.0"
edition = "2021"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
rusty_fractals_domain = { path = "../rusty_fractals_domain" }
rusty_fractals_image = { path = "../rusty_fractals_image" }
num_cpus = "0.2"
colored = "2"

[badges]
maintenance = { status = "actively-developed" }
