[package]
name = "rusty_fractals_core"
version = "0.1.0"
edition = "2021"
authors = ["lukas"]
keywords = ["fractal"]

[dependencies]
rusty_fractals_domain = { path = "../rusty_fractals_domain" }
rusty_fractals_result = { path = "../rusty_fractals_result" }
rusty_fractals_common = { path = "../rusty_fractals_common" }
num_cpus = "0.2"
colored = "2"
rayon = "1.5"
log4rs = "1.2.0"
log = "0.4.17"

[badges]
maintenance = { status = "actively-developed" }
